package watch

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
)

// newContentTestTracker builds a tracker whose churn threshold is set high
// enough that churn never trips during the content tests, so a quarantine can
// only come from the content detector. It uses a real-ish content config with
// small caps for fast, deterministic tests.
func newContentTestTracker(t *testing.T, cfg contentConfig) *QuarantineTracker {
	t.Helper()
	q, _ := newTestTracker(t)
	// Push churn far out of the way: content must be the only trip source.
	q.cfg.threshold = 1_000_000
	q.content = &contentDetector{
		cfg:   cfg,
		byDir: make(map[string]map[string]*dirContent),
	}
	return q
}

func defaultContentTestCfg() contentConfig {
	return contentConfig{
		minSamples:  4,
		sharePct:    90,
		sampleBytes: 64 * 1024,
		maxLine:     5000,
		maxSamples:  8,
	}
}

// writeFile creates path with content, making parent dirs as needed.
func writeFile(t *testing.T, path, content string) {
	t.Helper()
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(path, []byte(content), 0o644); err != nil {
		t.Fatal(err)
	}
}

// genFileContent returns a plausibly-machine-generated file body (explicit
// marker + minified single line).
func genFileContent(seed int) string {
	return "// @generated by tool\n" + strings.Repeat("a", 6000) + "\n"
}

func TestContent_GeneratedDirIsQuarantined(t *testing.T) {
	repo := t.TempDir()
	q := newContentTestTracker(t, defaultContentTestCfg())
	dir := filepath.Join(repo, "vendor", "bundle")

	quarantined := false
	for i := 0; i < 8; i++ {
		p := filepath.Join(dir, "gen"+string(rune('a'+i))+".js")
		writeFile(t, p, genFileContent(i))
		if q.Observe(repo, p) {
			quarantined = true
		}
	}
	if !quarantined {
		t.Fatalf("a dir of generated files should be quarantined")
	}
	list := q.List(repo)
	if len(list) != 1 || list[0].Rel != "vendor/bundle" || list[0].Signal != "content" {
		t.Fatalf("expected vendor/bundle quarantined with signal=content, got %+v", list)
	}
}

func TestContent_NormalSourceDirWithFewGeneratedIsNotQuarantined(t *testing.T) {
	repo := t.TempDir()
	q := newContentTestTracker(t, defaultContentTestCfg())
	dir := filepath.Join(repo, "src", "app")

	// 8 normal hand-written source files + 1 lockfile + 1 minified vendor file.
	// Generated share = 2/10 = 20% — far below the 90% bar.
	src := "package app\n\nfunc Handler() error {\n\treturn nil\n}\n"
	for i := 0; i < 8; i++ {
		p := filepath.Join(dir, "file"+string(rune('a'+i))+".go")
		writeFile(t, p, src)
		if q.Observe(repo, p) {
			t.Fatalf("normal source file %d unexpectedly quarantined the dir", i)
		}
	}
	lock := filepath.Join(dir, "package-lock.json")
	writeFile(t, lock, "{}")
	q.Observe(repo, lock)
	minified := filepath.Join(dir, "vendor.min.js")
	writeFile(t, minified, genFileContent(0))
	q.Observe(repo, minified)

	if len(q.List(repo)) != 0 {
		t.Fatalf("a normal source dir with a couple generated files must NOT be quarantined, got %+v", q.List(repo))
	}
}

func TestContent_PinnedDirNeverHealedButContentStillRespectsSet(t *testing.T) {
	// Pinned semantics are owned by the shared set; here we assert a pinned dir
	// already quarantined for content does not get auto-recovered.
	repo := t.TempDir()
	q := newContentTestTracker(t, defaultContentTestCfg())
	dir := filepath.Join(repo, "gen")
	for i := 0; i < 8; i++ {
		p := filepath.Join(dir, "g"+string(rune('a'+i))+".js")
		writeFile(t, p, genFileContent(i))
		q.Observe(repo, p)
	}
	if len(q.List(repo)) != 1 {
		t.Fatalf("setup: dir should be quarantined")
	}
	if !q.Pin(repo, "gen") {
		t.Fatalf("pin should succeed on a quarantined dir")
	}
	// Recover (query/reference) must NOT un-quarantine a pinned dir.
	if _, rec := q.Recover(repo, filepath.Join(dir, "ga.js")); rec {
		t.Fatalf("pinned dir must not be recovered on query")
	}
	if len(q.List(repo)) != 1 {
		t.Fatalf("pinned dir must remain quarantined")
	}
}

func TestContent_SamplingCapIsHonored(t *testing.T) {
	repo := t.TempDir()
	cfg := defaultContentTestCfg()
	cfg.minSamples = 100 // never reachable within the cap → cannot trip
	cfg.maxSamples = 5   // freeze after 5 samples
	q := newContentTestTracker(t, cfg)
	dir := filepath.Join(repo, "gen")

	// Fire 50 distinct generated files; the accumulator must freeze at 5 and
	// never trip (min-samples is unreachable), proving the per-dir cap bounds
	// the work.
	for i := 0; i < 50; i++ {
		p := filepath.Join(dir, "g"+string(rune('a'+(i%26)))+string(rune('a'+(i/26)))+".js")
		writeFile(t, p, genFileContent(i))
		if q.Observe(repo, p) {
			t.Fatalf("must not quarantine: min-samples unreachable")
		}
	}
	dc := q.content.byDir[repo]["gen"]
	if dc == nil {
		t.Fatalf("expected an accumulator for gen")
	}
	if !dc.frozen {
		t.Fatalf("accumulator should be frozen after the sample cap")
	}
	if dc.total > cfg.maxSamples {
		t.Fatalf("sampling cap not honored: total=%d > cap=%d", dc.total, cfg.maxSamples)
	}
}

func TestContent_SameFileRewrittenCountsOnce(t *testing.T) {
	repo := t.TempDir()
	q := newContentTestTracker(t, defaultContentTestCfg())
	dir := filepath.Join(repo, "gen")
	p := filepath.Join(dir, "only.js")
	writeFile(t, p, genFileContent(0))
	for i := 0; i < 20; i++ {
		q.Observe(repo, p)
	}
	dc := q.content.byDir[repo]["gen"]
	if dc == nil || dc.total != 1 {
		t.Fatalf("a churning single file must count once, got total=%v", dc)
	}
	if len(q.List(repo)) != 0 {
		t.Fatalf("one generated file must not quarantine (below min-samples)")
	}
}

func TestContent_DisabledIsNoOp(t *testing.T) {
	repo := t.TempDir()
	cfg := defaultContentTestCfg()
	cfg.disabled = true
	q := newContentTestTracker(t, cfg)
	q.content.cfg.disabled = true
	dir := filepath.Join(repo, "gen")
	for i := 0; i < 8; i++ {
		p := filepath.Join(dir, "g"+string(rune('a'+i))+".js")
		writeFile(t, p, genFileContent(i))
		q.Observe(repo, p)
	}
	if len(q.List(repo)) != 0 {
		t.Fatalf("disabled content detector must be a no-op")
	}
}

func TestContent_ClassifySignals(t *testing.T) {
	repo := t.TempDir()
	cfg := defaultContentTestCfg()

	cases := []struct {
		name    string
		content string
		gen     bool
	}{
		{"marker", "// Code generated by protoc. DO NOT EDIT.\npackage x\n", true},
		{"minified", strings.Repeat("x", 6000), true},
		{"binary", "abc\x00def\x00ghi", true},
		{"normal", "package app\n\nfunc Foo() {}\n", false},
	}
	for _, c := range cases {
		p := filepath.Join(repo, c.name+".txt")
		writeFile(t, p, c.content)
		gen, ok := classifyFile(p, cfg)
		if !ok {
			t.Fatalf("%s: expected sampleable", c.name)
		}
		if gen != c.gen {
			t.Fatalf("%s: classify gen=%v want %v", c.name, gen, c.gen)
		}
	}

	// Lockfile by basename, no content needed.
	lock := filepath.Join(repo, "go.sum")
	writeFile(t, lock, "github.com/x/y v1 h1:abc\n")
	if gen, ok := classifyFile(lock, cfg); !ok || !gen {
		t.Fatalf("go.sum should classify generated")
	}
}
