import { Link } from "react-router-dom";
import { ChevronLeft, ChevronRight, X } from "lucide-react";
import { Button } from "@/components/ui/button";
import type { RepositoryTopologyEdge, RepositoryTopologyFilters } from "@/data/types";
import { useRepositoryTopologyEdge } from "@/hooks/use-repository-topology";
import { repositoryRecordLinks } from "@/lib/repository-topology-view";

export function EdgeDetailPanel({ groupId, edge, filters, page, onPageChange, onClose }: { groupId: string; edge: RepositoryTopologyEdge; filters: RepositoryTopologyFilters; page: number; onPageChange: (page: number) => void; onClose: () => void }) {
  const detail = useRepositoryTopologyEdge(groupId, { source: edge.source, target: edge.target, channel: edge.channel, evidence: filters.evidence, search: filters.search, page, pageSize: 25 });
  const total = detail.data?.pagination.total ?? 0;
  const pages = Math.max(1, Math.ceil(total / 25));
  return <aside className="w-[26rem] shrink-0 overflow-y-auto border-l border-border bg-surface p-4"><div className="flex items-start justify-between"><div><h2 className="font-semibold text-text-1">{edge.source} → {edge.target}</h2><p className="text-xs uppercase text-text-3">{edge.channel} · {edge.relationship_count} relationships</p></div><Button size="sm" variant="ghost" onClick={onClose}><X size={14} /></Button></div>{detail.isError && <div className="mt-4 rounded border border-danger p-3 text-xs text-danger">Failed to load details. The topology remains available.<Button className="ml-2" size="sm" variant="secondary" onClick={() => detail.refetch()}>Retry</Button></div>}{detail.isLoading && <p className="mt-4 text-sm text-text-3">Loading evidence…</p>}<div className="mt-4 space-y-3">{detail.data?.data.map((record) => <article key={record.id} className="rounded border border-border p-3 text-xs"><div className="flex justify-between gap-2"><span className="font-medium text-text-1">{record.label}</span><span className="text-text-4">{record.evidence}</span></div>{record.identifier && <p className="mt-1 break-all font-mono text-[10px] text-text-3">{record.identifier}</p>}<div className="mt-2 flex flex-wrap gap-2">{repositoryRecordLinks(groupId, record).map((link) => <Link key={link.href} className="text-accent hover:underline" to={link.href}>{link.label}</Link>)}</div></article>)}</div>{!detail.isLoading && !detail.isError && total === 0 && <p className="mt-4 text-sm text-text-3">No matching evidence records.</p>}<div className="mt-4 flex items-center justify-between text-xs"><Button size="sm" variant="ghost" disabled={page <= 1} onClick={() => onPageChange(page - 1)}><ChevronLeft size={14} /> Previous</Button><span>{page} / {pages} · {total}</span><Button size="sm" variant="ghost" disabled={page >= pages} onClick={() => onPageChange(page + 1)}>Next <ChevronRight size={14} /></Button></div></aside>;
}
