/* ============================================================
   docs-empty.tsx — Docs screen empty states (#1552).

   Two cases:

   • DocsNotGenerated — the generate-docs SKILL has not run for this group,
     so there are zero documents. Docs are produced by the user's coding
     AGENT running the archigraph docs skill — there is NO CLI command.

   • DocsPickDocument — documents exist but none is selected yet.
   ============================================================ */

import { BookOpen, Sparkles } from "lucide-react";

// Whole-screen state: no documents have been generated for this group.
export function DocsNotGenerated() {
  return (
    <div className="flex flex-1 items-center justify-center px-6">
      <div className="flex flex-col items-center text-center max-w-md gap-4">
        <span className="text-text-4" aria-hidden="true">
          <Sparkles size={36} strokeWidth={1.25} />
        </span>
        <h2 className="text-lg font-medium text-text">No documentation yet</h2>
        <p className="text-sm text-text-3 leading-relaxed">
          Documentation is generated by your coding agent running the{" "}
          <span className="font-mono text-text-2">archigraph docs skill</span>.
          Ask your agent to generate docs for this group — it walks the
          knowledge graph and writes navigable markdown (overview, per-module
          deep-dives, API/reference, and patterns) into each repo&rsquo;s{" "}
          <span className="font-mono text-text-2">docs/</span> folder.
        </p>
        <p className="text-xs text-text-4 leading-relaxed">
          Once generation finishes, those documents appear here grouped by repo
          and category, with full markdown rendering in this pane. This screen
          shows the generated docs — there is no CLI command to run.
        </p>
      </div>
    </div>
  );
}

// Right-pane state: documents exist, but the user hasn't opened one.
export function DocsPickDocument() {
  return (
    <div className="flex flex-col items-center justify-center h-full gap-3 px-6 text-center">
      <span className="text-text-4" aria-hidden="true">
        <BookOpen size={32} strokeWidth={1.25} />
      </span>
      <h2 className="text-base font-medium text-text">Pick a document</h2>
      <p className="text-sm text-text-3 max-w-xs">
        Choose a document from the index on the left, or search by name above.
        Each page renders the markdown your coding agent generated.
      </p>
    </div>
  );
}
