/* ============================================================
   mermaid.tsx — Render a ```mermaid fenced block as an SVG diagram.

   The dependency-free Markdown renderer treats fenced code as literal text;
   mermaid blocks need the mermaid engine. To keep the main bundle lean,
   mermaid is LAZY-loaded (dynamic import) only when a doc actually contains a
   diagram — most doc pages have none.

   Theme: mermaid is initialized from the live <html data-theme> attribute
   (dark/light), and the diagram is re-rendered when the theme changes so it
   always matches the surrounding page. On parse/render error we fall back to a
   labeled code block (never crash the whole doc).
   ============================================================ */

import { useEffect, useRef, useState } from "react";

// Module-level singleton so we import + initialize mermaid at most once.
let mermaidPromise: Promise<typeof import("mermaid").default> | null = null;
let idCounter = 0;

function currentTheme(): "dark" | "light" {
  const t = document.documentElement.getAttribute("data-theme");
  return t === "dark" ? "dark" : "light";
}

async function loadMermaid() {
  if (!mermaidPromise) {
    mermaidPromise = import("mermaid").then((m) => m.default);
  }
  return mermaidPromise;
}

export function Mermaid({ code }: { code: string }) {
  const [svg, setSvg] = useState<string | null>(null);
  const [error, setError] = useState<string | null>(null);
  const [theme, setTheme] = useState<"dark" | "light">(() =>
    typeof document !== "undefined" ? currentTheme() : "light",
  );
  const idRef = useRef(`mmd-${idCounter++}`);

  // Re-render whenever the page theme flips (data-theme on <html>).
  useEffect(() => {
    const root = document.documentElement;
    const obs = new MutationObserver(() => {
      const next = currentTheme();
      setTheme((prev) => (prev === next ? prev : next));
    });
    obs.observe(root, { attributes: true, attributeFilter: ["data-theme"] });
    return () => obs.disconnect();
  }, []);

  useEffect(() => {
    let cancelled = false;
    setError(null);
    loadMermaid()
      .then(async (mermaid) => {
        mermaid.initialize({
          startOnLoad: false,
          securityLevel: "strict",
          theme: theme === "dark" ? "dark" : "default",
          fontFamily: "inherit",
        });
        // Mermaid v11 requires a unique id per render.
        const id = `${idRef.current}-${theme}`;
        const { svg } = await mermaid.render(id, code);
        if (!cancelled) setSvg(svg);
      })
      .catch((e: unknown) => {
        if (!cancelled) {
          setSvg(null);
          setError(e instanceof Error ? e.message : String(e));
        }
      });
    return () => {
      cancelled = true;
    };
  }, [code, theme]);

  // Fallback: show the source in a labeled block (never crash the doc).
  if (error) {
    return (
      <div className="my-3 rounded-md border border-border overflow-hidden">
        <div className="px-3 py-1.5 text-[0.7rem] uppercase tracking-wide text-text-4 bg-surface-2 border-b border-border">
          mermaid diagram (could not render)
        </div>
        <pre className="p-3 bg-surface-2 overflow-x-auto text-[0.8rem] leading-relaxed">
          <code className="font-mono text-text-2">{code}</code>
        </pre>
      </div>
    );
  }

  if (svg === null) {
    // Loading / rendering placeholder.
    return (
      <div className="my-3 flex items-center justify-center rounded-md border border-border bg-surface-2 py-8 text-sm text-text-4 animate-pulse">
        Rendering diagram…
      </div>
    );
  }

  return (
    <div
      className="my-4 flex justify-center overflow-x-auto rounded-md border border-border bg-surface p-3 [&_svg]:max-w-full [&_svg]:h-auto"
      // mermaid output is generated by us from doc source; securityLevel:"strict"
      // sanitizes the SVG. dangerouslySetInnerHTML is required to inject SVG.
      dangerouslySetInnerHTML={{ __html: svg }}
    />
  );
}
