// handlers_v2_docs.go — WebUI v2 generated-markdown docs endpoints.
//
// These endpoints serve the /g/:groupId/docs screen in webui-v2.
//
// IMPORTANT (#1552): The Docs screen renders the MARKDOWN DOCUMENTS produced
// by the `generate-docs` skill — NOT the entity graph. Docs are generated by
// the user's coding AGENT running the archigraph docs skill (there is no CLI
// command). The skill writes markdown under `<repo>/docs/`:
//
//	<repo>/docs/overview.md
//	<repo>/docs/modules/<module-slug>/README.md
//	<repo>/docs/reference/<section>.md
//	<repo>/docs/patterns/<category>/<id>.md
//	<repo>/docs/<cross-cutting>.md  (auth, logging, error-handling, …)
//
// These v2 endpoints reuse the on-disk doc resolution from handlers_docs.go
// (groupDocPaths / buildDocTree) and wrap it in the v2 success envelope. The
// v1 /api/docs/{group} portal endpoints are left completely untouched.
//
// Routes (registered in server.go under the v2 section):
//
//	GET  /api/v2/groups/{group}/docs/tree            → handleV2DocsTree
//	GET  /api/v2/groups/{group}/docs/page?path=...   → handleV2DocsPage
//
// POST /api/v2/groups/{group}/docs/generate is intentionally NOT implemented.
// Doc generation is performed by the coding agent via the archigraph docs
// skill, not by an HTTP endpoint or CLI command.

package dashboard

import (
	"net/http"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

// ── Wire shapes ────────────────────────────────────────────────────────────

// v2DocNode is one node in the generated-docs file tree. It mirrors the
// DocNode TypeScript interface in data/types.ts.
//
//	dir  → "folder"   (repo root, modules/, reference/, patterns/, …)
//	file → "doc"      (a renderable .md document; Path is its API key)
type v2DocNode struct {
	Type     string      `json:"type"` // "folder" | "doc"
	Name     string      `json:"name"` // display label
	Path     string      `json:"path,omitempty"`     // doc key for /docs/page?path=  (docs only)
	Category string      `json:"category,omitempty"` // top-level section: overview|modules|reference|patterns|guide
	Children []v2DocNode `json:"children,omitempty"`
}

// v2DocPageReply is the data payload for a single rendered doc page.
type v2DocPageReply struct {
	Path     string `json:"path"`
	Title    string `json:"title"`
	Markdown string `json:"markdown"`
}

// ── Handlers ───────────────────────────────────────────────────────────────

// handleV2DocsTree — GET /api/v2/groups/{group}/docs/tree
//
// Returns the tree of GENERATED markdown documents for the Docs screen left
// pane, grouped per-repo then by doc category (overview / modules / reference
// / patterns / guides). When no docs have been generated yet the tree is the
// empty array `[]` and the UI shows the agent-skill empty state.
func (s *Server) handleV2DocsTree(w http.ResponseWriter, r *http.Request) {
	group := r.PathValue("group")
	if _, err := s.graphs.GetGroup(group); err != nil {
		writeV2Err(w, http.StatusNotFound, "not_found", "group not found: "+group)
		return
	}

	docPaths, err := groupDocPaths(group)
	if err != nil {
		// No registered docs path → treat as "not generated yet".
		writeV2JSON(w, http.StatusOK, v2OK([]v2DocNode{}))
		return
	}

	roots := []v2DocNode{}
	// Deterministic repo order.
	slugs := make([]string, 0, len(docPaths))
	for slug := range docPaths {
		slugs = append(slugs, slug)
	}
	sort.Strings(slugs)

	for _, slug := range slugs {
		docPath := docPaths[slug]
		if docPath == "" {
			continue
		}
		if _, err := os.Stat(docPath); err != nil {
			continue
		}
		repoNode := buildV2DocTree(docPath, slug)
		if len(repoNode.Children) > 0 {
			roots = append(roots, repoNode)
		}
	}

	writeV2JSON(w, http.StatusOK, v2OK(roots))
}

// handleV2DocsPage — GET /api/v2/groups/{group}/docs/page?path=<repoSlug/rel/path.md>
//
// Returns the raw markdown of a single generated doc document. The {path}
// query param is the doc key emitted in the tree (repoSlug + "/" + relPath).
func (s *Server) handleV2DocsPage(w http.ResponseWriter, r *http.Request) {
	group := r.PathValue("group")
	rawPath := r.URL.Query().Get("path")
	if rawPath == "" {
		writeV2Err(w, http.StatusBadRequest, "bad_request", "path query param required")
		return
	}
	if _, err := s.graphs.GetGroup(group); err != nil {
		writeV2Err(w, http.StatusNotFound, "not_found", "group not found: "+group)
		return
	}

	docPaths, err := groupDocPaths(group)
	if err != nil {
		writeV2Err(w, http.StatusNotFound, "not_found", err.Error())
		return
	}

	// rawPath is "<repoSlug>/<rel...>" — split off the repo slug.
	slash := strings.IndexByte(rawPath, '/')
	if slash < 0 {
		writeV2Err(w, http.StatusBadRequest, "bad_request", "malformed doc path")
		return
	}
	repoSlug := rawPath[:slash]
	rel := rawPath[slash+1:]

	docPath, ok := docPaths[repoSlug]
	if !ok || docPath == "" {
		writeV2Err(w, http.StatusNotFound, "not_found", "unknown repo: "+repoSlug)
		return
	}

	// Sanitize: prevent path traversal.
	clean := filepath.Clean("/" + rel)
	target := filepath.Join(docPath, clean)
	if !strings.HasPrefix(target, docPath) {
		writeV2Err(w, http.StatusBadRequest, "bad_request", "invalid path")
		return
	}
	data, err := os.ReadFile(target)
	if err != nil {
		writeV2Err(w, http.StatusNotFound, "not_found", "doc not found: "+rawPath)
		return
	}

	reply := v2DocPageReply{
		Path:     rawPath,
		Title:    docTitleFromMarkdown(string(data), filepath.Base(target)),
		Markdown: string(data),
	}
	writeV2JSON(w, http.StatusOK, v2OK(reply))
}

// ── Helpers ────────────────────────────────────────────────────────────────

// docCategory maps a doc's relative path to a top-level section label used to
// group + order documents within a repo.
func docCategory(rel string) (label, key string) {
	r := filepath.ToSlash(rel)
	switch {
	case r == "overview.md" || r == "README.md":
		return "Overview", "overview"
	case strings.HasPrefix(r, "modules/"):
		return "Modules", "modules"
	case strings.HasPrefix(r, "reference/"):
		return "Reference", "reference"
	case strings.HasPrefix(r, "patterns/"):
		return "Patterns", "patterns"
	default:
		return "Guides", "guide"
	}
}

// categoryOrder gives a deterministic display order for doc sections.
func categoryOrder(key string) int {
	switch key {
	case "overview":
		return 0
	case "guide":
		return 1
	case "modules":
		return 2
	case "reference":
		return 3
	case "patterns":
		return 4
	default:
		return 9
	}
}

// buildV2DocTree walks a repo's docs directory and produces a category-grouped
// tree of renderable markdown documents. Only .md files become "doc" leaves;
// every leaf carries the API key (repoSlug + "/" + relPath) used by the page
// endpoint.
func buildV2DocTree(docRoot, repoSlug string) v2DocNode {
	// Collect every markdown file relative to docRoot, with its category.
	type docFile struct {
		rel     string
		catKey  string
		catName string
	}
	var files []docFile

	_ = filepath.Walk(docRoot, func(path string, info os.FileInfo, err error) error {
		if err != nil || info.IsDir() {
			return nil
		}
		name := info.Name()
		if strings.HasPrefix(name, ".") {
			return nil
		}
		if !strings.EqualFold(filepath.Ext(name), ".md") {
			return nil
		}
		rel, rerr := filepath.Rel(docRoot, path)
		if rerr != nil {
			return nil
		}
		// Skip enrichment frontmatter files — they back the graph surfaces,
		// not the human-readable docs portal.
		if strings.HasPrefix(filepath.ToSlash(rel), "enrichments/") {
			return nil
		}
		catName, catKey := docCategory(rel)
		files = append(files, docFile{rel: filepath.ToSlash(rel), catKey: catKey, catName: catName})
		return nil
	})

	// Group by category.
	byCat := map[string][]docFile{}
	catName := map[string]string{}
	for _, f := range files {
		byCat[f.catKey] = append(byCat[f.catKey], f)
		catName[f.catKey] = f.catName
	}

	cats := make([]string, 0, len(byCat))
	for k := range byCat {
		cats = append(cats, k)
	}
	sort.Slice(cats, func(i, j int) bool {
		oi, oj := categoryOrder(cats[i]), categoryOrder(cats[j])
		if oi != oj {
			return oi < oj
		}
		return cats[i] < cats[j]
	})

	repoNode := v2DocNode{Type: "folder", Name: repoSlug}
	for _, cat := range cats {
		group := byCat[cat]
		sort.Slice(group, func(i, j int) bool { return group[i].rel < group[j].rel })

		catNode := v2DocNode{Type: "folder", Name: catName[cat], Category: cat}
		for _, f := range group {
			catNode.Children = append(catNode.Children, v2DocNode{
				Type:     "doc",
				Name:     docLabel(f.rel),
				Path:     repoSlug + "/" + f.rel,
				Category: cat,
			})
		}
		repoNode.Children = append(repoNode.Children, catNode)
	}
	return repoNode
}

// docLabel produces a human-friendly label for a doc leaf from its rel path.
// e.g. "modules/order-service/README.md" → "order-service",
//
//	"reference/api.md" → "api", "overview.md" → "overview".
func docLabel(rel string) string {
	r := filepath.ToSlash(rel)
	base := filepath.Base(r)
	// For a directory README, label with the directory name instead.
	if strings.EqualFold(base, "README.md") {
		dir := filepath.Base(filepath.Dir(r))
		if dir != "." && dir != "" {
			return dir
		}
	}
	return strings.TrimSuffix(base, filepath.Ext(base))
}

// docTitleFromMarkdown returns the first H1 in the markdown, falling back to
// the filename (sans extension) when no heading is present.
func docTitleFromMarkdown(md, fallbackBase string) string {
	for _, line := range strings.Split(md, "\n") {
		t := strings.TrimSpace(line)
		if strings.HasPrefix(t, "# ") {
			return strings.TrimSpace(strings.TrimPrefix(t, "# "))
		}
	}
	return strings.TrimSuffix(fallbackBase, filepath.Ext(fallbackBase))
}
