package extractors

import (
	"context"
	"testing"

	"github.com/cajasmota/grafel/internal/extractor"
	"github.com/cajasmota/grafel/internal/types"
)

// #6329 — every entity extracted from a machine-generated file is stamped
// with the generated flag and the provenance of the rule that fired.
//
// The stamp lives in safeExtract because that is the ONE chokepoint every
// production extraction path funnels through: cmd/grafel/index.go via
// extractPass1 -> Extract, internal/daemon/extract/subproc.go via Extract, and
// internal/extractors/incremental.go which calls safeExtract directly (see the
// #6151 comment there for why it does).
//
// Putting the stamp in FileInput and asking 60 extractors to honour it would
// mean 60 opt-ins with a silent-ignore failure mode: an extractor that ignored
// the flag would emit unstamped entities and nothing would notice. Here no
// extractor is consulted, so none can forget.

type stubExtractor struct {
	lang string
	ents []types.EntityRecord
}

func (s stubExtractor) Language() string { return s.lang }
func (s stubExtractor) Extract(_ context.Context, _ extractor.FileInput) ([]types.EntityRecord, error) {
	out := make([]types.EntityRecord, len(s.ents))
	copy(out, s.ents)
	return out, nil
}

func registerStub(t *testing.T, lang string, ents []types.EntityRecord) {
	t.Helper()
	Register(lang, stubExtractor{lang: lang, ents: ents})
}

func twoEntities() []types.EntityRecord {
	return []types.EntityRecord{
		{Name: "User", Kind: string(types.EntityKindClass)},
		{Name: "GetName", Kind: string(types.EntityKindOperation), Properties: map[string]string{"visibility": "public"}},
	}
}

func TestExtract_StampsGeneratedOnPathMatch(t *testing.T) {
	registerStub(t, "gen6329_path", twoEntities())
	ents, err := Extract(context.Background(), FileInput{
		Path:     "api/v1/user.pb.go",
		Language: "gen6329_path",
		Content:  []byte("package v1\n\ntype User struct{}\n"),
	})
	if err != nil {
		t.Fatalf("Extract: %v", err)
	}
	if len(ents) != 2 {
		t.Fatalf("got %d entities, want 2", len(ents))
	}
	for _, e := range ents {
		if e.Properties[types.EntityGeneratedProperty] != "true" {
			t.Errorf("entity %q not stamped generated (properties=%v)", e.Name, e.Properties)
		}
		if e.Properties[types.EntityGeneratedByProperty] != "path:*.pb.go" {
			t.Errorf("entity %q provenance = %q, want %q",
				e.Name, e.Properties[types.EntityGeneratedByProperty], "path:*.pb.go")
		}
	}
	// Pre-existing properties survive the stamp.
	if ents[1].Properties["visibility"] != "public" {
		t.Errorf("stamp clobbered a pre-existing property: %v", ents[1].Properties)
	}
}

func TestExtract_StampsGeneratedOnContentMarker(t *testing.T) {
	registerStub(t, "gen6329_marker", twoEntities())
	// A filename NO rule matches — the marker alone must do the work. This is
	// the #6321 category: WSDL/XSD partials matching neither *.Designer.vb nor
	// Reference.vb.
	ents, err := Extract(context.Background(), FileInput{
		Path:     "Services/AccountsSoapClient.vb",
		Language: "gen6329_marker",
		Content:  []byte("' <auto-generated>\n'     This code was generated by a tool.\n' </auto-generated>\n"),
	})
	if err != nil {
		t.Fatalf("Extract: %v", err)
	}
	for _, e := range ents {
		if e.Properties[types.EntityGeneratedProperty] != "true" {
			t.Fatalf("entity %q not stamped from the content marker", e.Name)
		}
		if e.Properties[types.EntityGeneratedByProperty] != "marker:auto-generated-tag" {
			t.Fatalf("provenance = %q, want the marker rule",
				e.Properties[types.EntityGeneratedByProperty])
		}
	}
}

// TestExtract_HandWrittenFilesAreUntouched is the status-quo guarantee. A
// hand-written file must come back byte-identical to what the extractor
// emitted — no flag, no provenance, and no Properties map conjured onto an
// entity that had none. Allocating an empty map here would change what every
// downstream `len(e.Properties) == 0` check sees.
func TestExtract_HandWrittenFilesAreUntouched(t *testing.T) {
	registerStub(t, "gen6329_plain", twoEntities())
	ents, err := Extract(context.Background(), FileInput{
		Path:     "internal/mcp/scoring.go",
		Language: "gen6329_plain",
		Content:  []byte("package mcp\n\nfunc BuildBM25() {}\n"),
	})
	if err != nil {
		t.Fatalf("Extract: %v", err)
	}
	if ents[0].Properties != nil {
		t.Errorf("hand-written entity gained a Properties map: %v", ents[0].Properties)
	}
	for _, e := range ents {
		if _, ok := e.Properties[types.EntityGeneratedProperty]; ok {
			t.Errorf("hand-written entity %q carries the generated flag", e.Name)
		}
		if _, ok := e.Properties[types.EntityGeneratedByProperty]; ok {
			t.Errorf("hand-written entity %q carries generated provenance", e.Name)
		}
	}
}

// TestSafeExtract_StampsToo pins the incremental path specifically.
// incremental.go calls safeExtract directly rather than Extract (#6151), so a
// stamp applied only in Extract would leave the daemon's watcher-tick
// re-extraction unstamped — the graph would disagree with itself depending on
// whether a file arrived via a full index or a file-save.
func TestSafeExtract_StampsToo(t *testing.T) {
	ext := stubExtractor{lang: "gen6329_safe", ents: twoEntities()}
	ents, err := safeExtract(context.Background(), ext, FileInput{
		Path:    "internal/di/wire_gen.go",
		Content: []byte("package di\n"),
	})
	if err != nil {
		t.Fatalf("safeExtract: %v", err)
	}
	for _, e := range ents {
		if e.Properties[types.EntityGeneratedProperty] != "true" {
			t.Fatalf("incremental path did not stamp entity %q", e.Name)
		}
	}
}

// TestExtract_StampSurvivesNilContent — the classifier hands subproc a path
// before the read in some orderings, and a caller may pass no content at all.
// The path rule must still fire; the marker pass must not panic.
func TestExtract_StampSurvivesNilContent(t *testing.T) {
	registerStub(t, "gen6329_nilcontent", twoEntities())
	ents, err := Extract(context.Background(), FileInput{
		Path:     "proto/user_pb2.py",
		Language: "gen6329_nilcontent",
		Content:  nil,
	})
	if err != nil {
		t.Fatalf("Extract: %v", err)
	}
	if ents[0].Properties[types.EntityGeneratedProperty] != "true" {
		t.Fatal("path rule did not fire with nil content")
	}
}
