package main

import (
	"os"
	"path/filepath"
	"sort"
	"testing"

	"github.com/cajasmota/grafel/internal/graph"
	"github.com/cajasmota/grafel/internal/testsupport"
	"github.com/cajasmota/grafel/internal/types"
)

// generatedSeamFixture writes a repository whose generated files produce
// entities in MORE than one pass, and one authored file that must stay clean.
//
// The Python file is the load-bearing one. It carries a marker header (so the
// content signal fires, not just a filename rule), it declares Django models
// and a DRF viewset, and it is imported by a sibling — which puts it in front
// of Pass 1 (the python extractor), Pass 2.5 (the YAML framework rules) and
// Pass 3 (the cross-language extractors) simultaneously.
func generatedSeamFixture(t *testing.T) string {
	t.Helper()
	root := t.TempDir()
	write := func(rel, body string) {
		p := filepath.Join(root, filepath.FromSlash(rel))
		if err := os.MkdirAll(filepath.Dir(p), 0o755); err != nil {
			t.Fatal(err)
		}
		if err := os.WriteFile(p, []byte(body), 0o644); err != nil {
			t.Fatal(err)
		}
	}

	write("app/generated_models.py", `# Code generated by sqlc. DO NOT EDIT.
# source: schema.sql

from django.db import models
from rest_framework import viewsets, serializers


class Customer(models.Model):
    name = models.CharField(max_length=200)
    email = models.EmailField(unique=True)

    class Meta:
        db_table = "customer"


class Invoice(models.Model):
    customer = models.ForeignKey(Customer, on_delete=models.CASCADE)
    total = models.DecimalField(max_digits=10, decimal_places=2)

    class Meta:
        db_table = "invoice"


class CustomerSerializer(serializers.ModelSerializer):
    class Meta:
        model = Customer
        fields = "__all__"


class CustomerViewSet(viewsets.ModelViewSet):
    queryset = Customer.objects.all()
    serializer_class = CustomerSerializer

    def list(self, request):
        return Customer.objects.filter(name__startswith="a")
`)

	write("app/urls.py", `from django.urls import path, include
from rest_framework.routers import DefaultRouter

from .generated_models import CustomerViewSet

router = DefaultRouter()
router.register(r"customers", CustomerViewSet)

urlpatterns = [
    path("", include(router.urls)),
]
`)

	write("api/user.pb.gw.go", `// Code generated by protoc-gen-grpc-gateway. DO NOT EDIT.
// source: user.proto

package gw

import (
	"context"
	"net/http"
)

// RegisterUserServiceHandlerServer registers the http handlers.
func RegisterUserServiceHandlerServer(ctx context.Context, mux *http.ServeMux) error {
	mux.HandleFunc("/v1/users", func(w http.ResponseWriter, r *http.Request) {})
	return nil
}
`)

	write("internal/svc/handler.go", `package svc

import "net/http"

// AuthoredHandler is hand-written and must never carry the generated flag.
func AuthoredHandler(w http.ResponseWriter, r *http.Request) {
	_ = r
	w.WriteHeader(http.StatusOK)
}
`)
	return root
}

func entitiesFrom(doc *graph.Document, rel string) []graph.Entity {
	var out []graph.Entity
	for _, e := range doc.Entities {
		if e.SourceFile == rel {
			out = append(out, e)
		}
	}
	return out
}

// TestGeneratedFlag_CoversEveryPass is the #6329 seam invariant.
//
// IT IS AN INVARIANT OVER ENTITIES, NOT A LIST OF CALL SITES, and that is the
// whole point. The first cut of this feature stamped the flag in
// extractors.safeExtract and claimed that was "the one chokepoint all three
// production paths funnel through". It covered Pass 1. Pass 2.5 (the YAML
// framework rules) and Pass 3 (the cross-language extractors) emit
// EntityRecords for the same file on both production paths without ever
// touching safeExtract, so *.pb.gw.go carried a pathRules entry while the
// grpc-gateway endpoints extracted from it went unstamped and undemoted —
// exactly the category the issue was filed about.
//
// A test that enumerated the call sites would have gone stale the moment a
// pass was added. This one asserts that EVERY entity attributed to a generated
// file carries the flag, whatever produced it, so a new pass is covered or the
// test fails.
//
// MUTATION TARGET: make Pass 2.5 or Pass 3 skip the stamp — or remove the
// gen.Stamp call from mergePassRecords — and this must fail.
func TestGeneratedFlag_CoversEveryPass(t *testing.T) {
	testsupport.IsolateHome(t)
	root := generatedSeamFixture(t)
	doc := runIndexerOn(t, root, "seamrepo", nil)

	generatedFiles := []string{"app/generated_models.py", "api/user.pb.gw.go"}
	for _, rel := range generatedFiles {
		ents := entitiesFrom(doc, rel)
		if len(ents) == 0 {
			t.Fatalf("%s produced no entities at all; the fixture is not exercising the pipeline", rel)
		}
		var unstamped []string
		for _, e := range ents {
			if e.PropGet(types.EntityGeneratedProperty) != "true" {
				unstamped = append(unstamped, e.Kind+" "+e.Name)
			}
			if by := e.PropGet(types.EntityGeneratedByProperty); e.PropGet(types.EntityGeneratedProperty) == "true" && by == "" {
				t.Errorf("%s: entity %s %q is flagged but carries no provenance", rel, e.Kind, e.Name)
			}
		}
		if len(unstamped) > 0 {
			sort.Strings(unstamped)
			t.Errorf("%s: %d of %d entities are NOT flagged as generated:\n  %v",
				rel, len(unstamped), len(ents), unstamped)
		}
	}

	// The authored file must stay clean — a stamp that fired on everything
	// would satisfy the loop above for free.
	for _, e := range entitiesFrom(doc, "internal/svc/handler.go") {
		if e.PropGet(types.EntityGeneratedProperty) != "" {
			t.Errorf("authored entity %s %q carries generated=%q",
				e.Kind, e.Name, e.PropGet(types.EntityGeneratedProperty))
		}
	}
}

// TestGeneratedSeamFixture_ActuallySpansMultiplePasses is the vacuity gate for
// the test above.
//
// The invariant "every entity from this file is flagged" is trivially true if
// the file only ever produces Pass 1 entities — which is precisely the state
// the original implementation was in, and precisely why its own tests could
// not see the gap. There is no pass label on an EntityRecord to assert
// against, so the gate is differential: index the same fixture with Pass 2.5
// and Pass 3 disabled, and require the full run to attribute STRICTLY MORE
// entities to the generated file than the Pass-1-only run does.
//
// If this test ever fails, the invariant test above has gone vacuous and must
// not be trusted, whatever its own result says.
func TestGeneratedSeamFixture_ActuallySpansMultiplePasses(t *testing.T) {
	testsupport.IsolateHome(t)
	root := generatedSeamFixture(t)

	full := runIndexerOn(t, root, "seamrepo", nil)
	pass1Only := runIndexerOn(t, root, "seamrepo", []string{"framework,cross-lang"})

	for _, rel := range []string{"app/generated_models.py", "api/user.pb.gw.go"} {
		nFull := len(entitiesFrom(full, rel))
		nP1 := len(entitiesFrom(pass1Only, rel))
		t.Logf("%s: pass1-only=%d full=%d", rel, nP1, nFull)
		if nFull <= nP1 {
			t.Errorf("%s contributes no entities beyond Pass 1 (pass1-only=%d, full=%d); "+
				"TestGeneratedFlag_CoversEveryPass is vacuous for this file",
				rel, nP1, nFull)
		}
	}
}
