// Command incrfixture generates a deterministic synthetic Go repository large
// enough for the incremental-vs-full reindex paths to separate (issue #6199).
//
// The existing perf test (internal/extractors/incremental_perf_test.go:78-88)
// disclaims itself: "on a 10-file fixture there is no measurable separation
// between 'incremental' and 'degenerated into a full reindex' … needs a fixture
// big enough for the two paths to separate — a few thousand files, not ten."
// This is that fixture.
//
// Why synthetic rather than a real repo: it is deterministic (same bytes for the
// same -files/-seed, so two measurements are comparable), it is shareable (no
// clone, no network, no confidentiality question), and its size is a dial rather
// than an accident.
//
// Shape. Files are spread over -pkgs packages under pkg/pNNN/. Each file
// carries a struct, an interface, a constructor, a handful of methods and a
// handful of free functions, and calls into two OTHER packages — so the graph
// gets real cross-file CALLS/REFERENCES edges rather than a pile of islands
// (an island graph would make the resolver and flow phases look free). Every
// eighth file is a _test.go so the coverage reachability pass has TESTS edges to
// walk.
//
// Usage:
//
//	go run internal/extractors/testdata/incrfixture/main.go \
//	    -out /tmp/fixture -files 3000 -pkgs 60 -seed 1 -git
//
// The generated tree is a self-contained Go module. -git initialises a repo and
// makes one commit, which the incremental path needs: diff.FilterWithGit shells
// out to `git diff --name-only HEAD`, and diff.HeadCommit must resolve.
package main

import (
	"flag"
	"fmt"
	"math/rand"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
)

func main() {
	out := flag.String("out", "", "output directory (must not exist, or -force)")
	files := flag.Int("files", 3000, "number of generated source files")
	pkgs := flag.Int("pkgs", 60, "number of packages to spread them over")
	seed := flag.Int64("seed", 1, "PRNG seed — same seed + same flags = same bytes")
	doGit := flag.Bool("git", true, "git init + one commit")
	force := flag.Bool("force", false, "delete -out first if it exists")
	flag.Parse()

	if *out == "" {
		fmt.Fprintln(os.Stderr, "incrfixture: -out is required")
		os.Exit(2)
	}
	if *force {
		if err := os.RemoveAll(*out); err != nil {
			die(err)
		}
	}
	if _, err := os.Stat(*out); err == nil {
		fmt.Fprintf(os.Stderr, "incrfixture: %s exists (use -force)\n", *out)
		os.Exit(2)
	}

	rng := rand.New(rand.NewSource(*seed))

	if err := os.MkdirAll(*out, 0o755); err != nil {
		die(err)
	}
	write(filepath.Join(*out, "go.mod"), "module grafelfixture\n\ngo 1.22\n")
	write(filepath.Join(*out, "README.md"),
		"# grafel incremental measurement fixture\n\nGenerated by internal/extractors/testdata/incrfixture. Do not edit by hand.\n")

	nTest := 0
	for i := 0; i < *files; i++ {
		p := i % *pkgs
		pkgName := fmt.Sprintf("p%03d", p)
		dir := filepath.Join(*out, "pkg", pkgName)
		if err := os.MkdirAll(dir, 0o755); err != nil {
			die(err)
		}
		// Two callee packages, deterministic but not the file's own.
		a := (p + 1 + rng.Intn(*pkgs-1)) % *pkgs
		b := (p + 1 + rng.Intn(*pkgs-1)) % *pkgs
		if i%8 == 7 {
			nTest++
			write(filepath.Join(dir, fmt.Sprintf("mod%05d_test.go", i)), testFile(pkgName, i))
			continue
		}
		write(filepath.Join(dir, fmt.Sprintf("mod%05d.go", i)), srcFile(pkgName, i, a, b, rng))
	}

	// One entry point so the flow walkers have a seed to start from.
	if err := os.MkdirAll(filepath.Join(*out, "cmd", "app"), 0o755); err != nil {
		die(err)
	}
	write(filepath.Join(*out, "cmd", "app", "main.go"), mainFile(*pkgs))

	if *doGit {
		gitInit(*out)
	}
	fmt.Printf("incrfixture: wrote %d files (%d tests) in %d packages to %s\n", *files+2, nTest, *pkgs, *out)
}

func srcFile(pkg string, i, a, b int, rng *rand.Rand) string {
	var s strings.Builder
	fmt.Fprintf(&s, "package %s\n\n", pkg)
	fmt.Fprintf(&s, "import (\n\t\"fmt\"\n\t\"strings\"\n\n")
	fmt.Fprintf(&s, "\tpa \"grafelfixture/pkg/p%03d\"\n", a)
	if b != a {
		fmt.Fprintf(&s, "\tpb \"grafelfixture/pkg/p%03d\"\n", b)
	}
	fmt.Fprintf(&s, ")\n\n")

	fmt.Fprintf(&s, "// Rec%05d is a generated record type.\ntype Rec%05d struct {\n", i, i)
	nf := 3 + rng.Intn(5)
	for f := 0; f < nf; f++ {
		fmt.Fprintf(&s, "\tField%d string\n", f)
	}
	fmt.Fprintf(&s, "\tCount int\n}\n\n")

	fmt.Fprintf(&s, "// Handler%05d is a generated interface.\ntype Handler%05d interface {\n\tHandle%05d(in string) (string, error)\n\tName%05d() string\n}\n\n", i, i, i, i)

	fmt.Fprintf(&s, "// NewRec%05d constructs a Rec%05d.\nfunc NewRec%05d(v string) *Rec%05d {\n\treturn &Rec%05d{Field0: v, Count: %d}\n}\n\n", i, i, i, i, i, i%17)

	fmt.Fprintf(&s, "func (r *Rec%05d) Handle%05d(in string) (string, error) {\n\tif in == \"\" {\n\t\treturn \"\", fmt.Errorf(\"empty input for %%d\", r.Count)\n\t}\n\treturn strings.ToUpper(in) + r.Field0, nil\n}\n\n", i, i)
	fmt.Fprintf(&s, "func (r *Rec%05d) Name%05d() string {\n\treturn %q\n}\n\n", i, i, fmt.Sprintf("rec-%05d", i))

	// Free functions; some call into the two imported packages so the graph has
	// real cross-package edges for the scoped resolver and flow passes to chase.
	nfn := 4 + rng.Intn(4)
	for f := 0; f < nfn; f++ {
		fmt.Fprintf(&s, "// Op%05d_%d is a generated operation.\nfunc Op%05d_%d(x int) int {\n", i, f, i, f)
		switch f % 3 {
		case 0:
			fmt.Fprintf(&s, "\treturn pa.Seed%03d(x) + x*%d\n", a, f+1)
		case 1:
			if b != a {
				fmt.Fprintf(&s, "\treturn pb.Seed%03d(x) - x\n", b)
			} else {
				fmt.Fprintf(&s, "\treturn pa.Seed%03d(x) - x\n", a)
			}
		default:
			fmt.Fprintf(&s, "\tr := NewRec%05d(\"x\")\n\ts, _ := r.Handle%05d(\"y\")\n\treturn len(s) + x\n", i, i)
		}
		fmt.Fprintf(&s, "}\n\n")
	}

	// Exactly one file per package defines the package's Seed function that the
	// other packages call. i/pkgs==0 picks the first file laid down in each.
	if i < 200 {
		fmt.Fprintf(&s, "// Seed%s is the per-package entry other packages call.\nfunc Seed%s(x int) int {\n\treturn x*2 + %d\n}\n", strings.TrimPrefix(pkg, "p"), strings.TrimPrefix(pkg, "p"), i)
	}
	return s.String()
}

func testFile(pkg string, i int) string {
	return fmt.Sprintf(`package %s

import "testing"

func TestOp%05d(t *testing.T) {
	r := NewRec%05d("v")
	if got := r.Name%05d(); got == "" {
		t.Fatalf("empty name")
	}
	if _, err := r.Handle%05d("in"); err != nil {
		t.Fatal(err)
	}
}
`, pkg, i, i-1, i-1, i-1)
}

func mainFile(pkgs int) string {
	var s strings.Builder
	s.WriteString("package main\n\nimport (\n\t\"fmt\"\n\n")
	n := pkgs
	if n > 20 {
		n = 20
	}
	for p := 0; p < n; p++ {
		fmt.Fprintf(&s, "\tp%03d \"grafelfixture/pkg/p%03d\"\n", p, p)
	}
	s.WriteString(")\n\nfunc main() {\n\ttotal := 0\n")
	for p := 0; p < n; p++ {
		fmt.Fprintf(&s, "\ttotal += p%03d.Seed%03d(1)\n", p, p)
	}
	s.WriteString("\tfmt.Println(total)\n}\n")
	return s.String()
}

func write(path, content string) {
	if err := os.WriteFile(path, []byte(content), 0o644); err != nil {
		die(err)
	}
}

func gitInit(dir string) {
	for _, args := range [][]string{
		{"init", "-q", "-b", "main"},
		{"config", "user.email", "fixture@example.invalid"},
		{"config", "user.name", "incrfixture"},
		{"add", "-A"},
		{"commit", "-q", "-m", "fixture"},
	} {
		cmd := exec.Command("git", args...)
		cmd.Dir = dir
		cmd.Env = append(os.Environ(), "GIT_CONFIG_GLOBAL=/dev/null", "GIT_CONFIG_SYSTEM=/dev/null")
		if out, err := cmd.CombinedOutput(); err != nil {
			fmt.Fprintf(os.Stderr, "incrfixture: git %v: %v\n%s\n", args, err, out)
			os.Exit(1)
		}
	}
}

func die(err error) {
	fmt.Fprintln(os.Stderr, "incrfixture:", err)
	os.Exit(1)
}
