package feedback

import (
	"context"
	"strings"
	"testing"

	"github.com/cajasmota/grafel/internal/graph"
	"github.com/cajasmota/grafel/internal/resolve"
)

// TestGenerate_GoldenFB is the regression guard for issue #5683 (D1/D2/D3). It
// runs feedback.Generate over a REAL graph.fb-loaded document — not a hand-built
// in-memory fixture — and asserts that the three collector metrics that read
// fields which do not survive the FB round-trip now report real values.
//
// The fixture (testdata/golden/graph.fb) is a genuine graph.fb: it was produced
// by round-tripping an indexed multi-language golden graph through the real
// fbwriter, so it speaks the production dialect the unit fixtures used to lie
// about — canonical SCOPE.* / bare kinds, no Properties["resolution"] tag, and
// ToID-shaped resolution.
//
// Every entity in it also carries EndLine == 0. That was once a property of the
// FB path itself: the Entity table had no end-line slot, so the value could not
// survive. #6236 added the slot, so it is no longer true of graph.fb in general.
//
// It is NOT a legacy artefact either (#6827 — an earlier version of this note
// implied it was). This fixture was REGENERATED by #6236 itself (a12a59321) and
// is a v6 file; a pre-v6 graph.fb would not load at all, since load.go's
// minSupportedFBFormatVersion is fbversion.Version. So the span-lessness below
// is a live observation of the CURRENT writer round-tripping a real
// multi-language graph — 0 of 672 entities with an end line — and it is the
// only measurement backing the source-window metric's one-sided check
// (report.go). That is what keeps D1 honest, and the sanity check below pins it.
//
// Against the pre-#5683 collector this test FAILS on all three axes:
//   - D1: source-window completeness == 0.0% (EndLine > StartLine never holds).
//   - D2: field-extraction ClassTotal == 0 ("No class or model entities found").
//   - D3: ResolutionTotal == 0 ("no resolution property found on edges").
func TestGenerate_GoldenFB(t *testing.T) {
	doc, err := graph.LoadGraphFromDir("testdata/golden")
	if err != nil {
		t.Fatalf("LoadGraphFromDir(testdata/golden): %v", err)
	}
	if len(doc.Entities) == 0 || len(doc.Relationships) == 0 {
		t.Fatalf("golden graph.fb empty: %d entities, %d rels", len(doc.Entities), len(doc.Relationships))
	}

	// Sanity: confirm the fixture is still span-less — no entity carries an
	// EndLine, and the class/model kinds are canonical (not lowercase). This is
	// what makes the assertions below meaningful regressions.
	for i := range doc.Entities {
		if doc.Entities[i].EndLine != 0 {
			t.Fatalf("fixture is no longer span-less: entity %s has EndLine=%d (expected 0)",
				doc.Entities[i].ID, doc.Entities[i].EndLine)
		}
	}

	r, err := Generate(context.Background(), []*graph.Document{doc}, Opts{GroupName: "golden"})
	if err != nil {
		t.Fatalf("Generate: %v", err)
	}
	if r.IsSuppressed() {
		t.Fatalf("golden report unexpectedly suppressed (entities=%d)", r.TotalEntities)
	}

	// --- D1: source-window completeness must be > 0 -------------------------
	if r.SourceWindow.TotalWithWindow == 0 || r.SourceWindow.PctComplete <= 0 {
		t.Errorf("D1: source-window completeness is zero (with-window=%d, pct=%.1f%%); "+
			"StartLine anchor should be counted", r.SourceWindow.TotalWithWindow, r.SourceWindow.PctComplete)
	}
	// Cross-check against a direct StartLine count.
	wantWindow := 0
	for i := range doc.Entities {
		if doc.Entities[i].StartLine > 0 {
			wantWindow++
		}
	}
	if r.SourceWindow.TotalWithWindow != wantWindow {
		t.Errorf("D1: with-window=%d, want %d (entities with StartLine>0)",
			r.SourceWindow.TotalWithWindow, wantWindow)
	}

	// --- D2: field-extraction must find the class/model entities ------------
	if r.FieldExtractionRate.ClassTotal == 0 {
		t.Errorf("D2: field-extraction found no class/model entities in a graph with Model + SCOPE.Schema kinds")
	}
	// Field LEAVES (Subtype == "field") are themselves class/model/schema-tail
	// kinds (SCOPE.Schema) but are not class/model CONTAINERS — they must be
	// excluded from the class-like count (Fix 1), or every field doubles as a
	// "class" and the zero-fields rate is guaranteed to read 100%. The same
	// holds for the other exempt subtypes (enum/const/file/import/delegate,
	// interface outside Kotlin, and the non-field-bearing languages — #6536).
	//
	// TAUTOLOGY WARNING — this check is NOT coverage of the exemption set.
	// It recomputes the expectation from the same production predicate that
	// Generate uses, so a wrong kind tail or a wrong exemption cannot make it
	// fail; all it asserts is that Generate calls this predicate and counts the
	// result. It was already half-tautological before #6536 and lost its last
	// literal there. The real pins for the predicate live in
	// report_classlike_component_6536_test.go, which takes its kinds from the
	// extractors. Rebuilding this into an independent expectation is out of
	// scope for #6536 and tracked separately.
	wantClassLike := 0
	for i := range doc.Entities {
		e := &doc.Entities[i]
		if isFieldExtractionCandidate(e.Kind, e.Subtype, e.Language) {
			wantClassLike++
		}
	}
	if r.FieldExtractionRate.ClassTotal != wantClassLike {
		t.Errorf("D2: ClassTotal=%d, want %d (class/model/schema-like kinds, excluding non-container subtypes)",
			r.FieldExtractionRate.ClassTotal, wantClassLike)
	}

	// --- D3: resolution disposition must be non-empty and match ToID shape --
	if r.ResolutionTotal == 0 {
		t.Errorf("D3: ResolutionTotal is zero; disposition must be derived from ToID shape")
	}
	if r.Resolution.Pct("bug-extractor") == 0 && r.Resolution.Pct("resolved") == 0 && r.Resolution.Pct("external-known") == 0 {
		t.Errorf("D3: resolution vector is all-zero; expected a resolved/external/unresolved split")
	}
	// D3a — the `resolved` bucket must equal the HEX-ToID fraction exactly.
	// classifyDispositionLang short-circuits on isHexID before it looks at
	// anything else, and isHexID is the same 16-lowercase-hex test
	// IsResolvedToID applies, so this is an identity and not an approximation.
	//
	// This clause used to compare resolved+external against the whole of
	// IsResolvedToID (hex OR "ext:"). That comparison is no longer valid, and its
	// failure is the POINT of #6836: the report now runs the indexer's real
	// classifier, which routes ext:-stamped reflection builtins to `dynamic`
	// rather than to an external bucket (#95). Six ext:-stamped edges are
	// routed that way; the NET effect on this identity is four, because two
	// non-ext: stdlib callees move the other way into external-known. An
	// ext:-inclusive identity would now be asserting the bug.
	var total, hexResolved, extPrefixed int
	for i := range doc.Relationships {
		toID := doc.Relationships[i].ToID
		if toID == "" {
			continue
		}
		total++
		switch {
		case len(toID) == 16 && resolve.IsHexString(toID):
			hexResolved++
		case strings.HasPrefix(toID, "ext:"):
			extPrefixed++
		}
	}
	if total == 0 {
		t.Fatal("D3: no non-empty ToID edges in fixture")
	}
	if r.ResolutionTotal != total {
		t.Errorf("D3: ResolutionTotal=%d, want %d (non-empty-ToID edges)", r.ResolutionTotal, total)
	}
	wantResolvedPct := 100.0 * float64(hexResolved) / float64(total)
	gotResolvedPct := r.Resolution.Pct("resolved")
	if diff := gotResolvedPct - wantResolvedPct; diff > 0.01 || diff < -0.01 {
		t.Errorf("D3a: resolved = %.3f%%, want %.3f%% (hex-ToID fraction)",
			gotResolvedPct, wantResolvedPct)
	}

	// D3b — the three dispositions #6836 found dead must be ALIVE on real data.
	// Before the fix external-unknown, bug-resolver and dynamic were wired to
	// counters nothing incremented and rendered a permanent 0.00%; on this
	// fixture they carry 53 + 17 + 90 of 796 edges (measured on THIS branch —
	// 59 was the pre-TrimPrefix external-unknown count). A hand-built fixture
	// alone
	// would not have caught the original defect, because the defect was that no
	// corpus could ever move these.
	for _, d := range []string{"external-unknown", "bug-resolver", "dynamic"} {
		if r.Resolution.Pct(d) <= 0 {
			t.Errorf("D3b: %s is %.3f%% on the golden fixture — #6836 regression (it was a permanently dead counter)",
				d, r.Resolution.Pct(d))
		}
	}
	if extPrefixed == 0 {
		t.Fatal("D3b: fixture has no ext:-prefixed edges, so the external split is untested here")
	}

	t.Logf("golden FB: entities=%d rels=%d | D1 window=%.1f%% (%d) | D2 classLike=%d | D3 total=%d resolved+ext=%.2f%% bug=%.2f%%",
		len(doc.Entities), len(doc.Relationships),
		r.SourceWindow.PctComplete, r.SourceWindow.TotalWithWindow,
		r.FieldExtractionRate.ClassTotal,
		r.ResolutionTotal, gotResolvedPct, r.Resolution.Pct("bug-extractor"))
}
