// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package service

import (
	"context"

	"example.com/app/query"
)

// Generated typed-query API usage (what application code looks like with gen).
func listActiveUsers(ctx context.Context, q *query.Query) error {
	users, err := q.User.Where(q.User.Active.Eq(true)).Order(q.User.Name).Find()
	if err != nil {
		return err
	}
	_ = users

	first, err := q.User.Where(q.User.ID.Gt(0)).First()
	_ = first

	posts, _ := q.Post.Where(q.Post.Title.Like("%go%")).Limit(10).Find()
	_ = posts

	// Standalone (non-chained) typed calls — directly q.<Model>.<Op>(...).
	count, _ := q.User.Count()
	_ = count

	_, err = q.Post.Delete()
	return err
}
