// Code generated by goctl. DO NOT EDIT.
// goctl 1.6.0

package handler

import (
	"net/http"

	user "example.com/api/internal/handler/user"
	"example.com/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/users/:id",
				Handler: user.GetUserHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/users",
				Handler: user.CreateUserHandler(serverCtx),
			},
			{
				Method:  http.MethodDelete,
				Path:    "/users/:id",
				Handler: user.DeleteUserHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/v1"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  "GET",
				Path:    "/health",
				Handler: HealthHandler(serverCtx),
			},
		},
	)
}
