// Code generated by protoc-gen-go-http. DO NOT EDIT.
// source: helloworld/v1/greeter.proto

package v1

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
)

const _ = http.SupportPackageIsVersion1

const OperationGreeterSayHello = "/helloworld.v1.Greeter/SayHello"
const OperationGreeterListGreetings = "/helloworld.v1.Greeter/ListGreetings"

type GreeterHTTPServer interface {
	SayHello(context.Context, *HelloRequest) (*HelloReply, error)
	ListGreetings(context.Context, *ListRequest) (*ListReply, error)
	CreateGreeting(context.Context, *CreateRequest) (*HelloReply, error)
	DeleteGreeting(context.Context, *DeleteRequest) (*emptypb.Empty, error)
}

func RegisterGreeterHTTPServer(s *http.Server, srv GreeterHTTPServer) {
	r := s.Route("/")
	r.GET("/helloworld/{name}", _Greeter_SayHello0_HTTP_Handler(srv))
	r.GET("/greetings", _Greeter_ListGreetings0_HTTP_Handler(srv))
	r.POST("/greetings", _Greeter_CreateGreeting0_HTTP_Handler(srv))
	r.DELETE("/greetings/{id}", _Greeter_DeleteGreeting0_HTTP_Handler(srv))
}

func _Greeter_SayHello0_HTTP_Handler(srv GreeterHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in HelloRequest
		return ctx.Result(200, nil)
	}
}

func _Greeter_ListGreetings0_HTTP_Handler(srv GreeterHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error { return nil }
}

func _Greeter_CreateGreeting0_HTTP_Handler(srv GreeterHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error { return nil }
}

func _Greeter_DeleteGreeting0_HTTP_Handler(srv GreeterHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error { return nil }
}
