// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: query.sql

package db

import "context"

const getAuthor = `-- name: GetAuthor :one
SELECT id, name, bio, created_at FROM authors WHERE id = $1
`

func (q *Queries) GetAuthor(ctx context.Context, id int64) (Author, error) {
	row := q.db.QueryRowContext(ctx, getAuthor, id)
	var i Author
	err := row.Scan(&i.ID, &i.Name, &i.Bio, &i.CreatedAt)
	return i, err
}

const listBooks = `-- name: ListBooks :many
SELECT id, author_id, title FROM books ORDER BY title
`

func (q *Queries) ListBooks(ctx context.Context) ([]Book, error) {
	return nil, nil
}

const deleteAuthor = `-- name: DeleteAuthor :exec
DELETE FROM authors WHERE id = $1
`

func (q *Queries) DeleteAuthor(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteAuthor, id)
	return err
}
