// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package db

import (
	"database/sql"
	"time"
)

type Author struct {
	ID        int64
	Name      string
	Bio       sql.NullString
	CreatedAt time.Time
}

type Book struct {
	ID       int64
	AuthorID int64
	Title    string
}

// Queries is the sqlc-generated query holder; not a model.
type Queries struct {
	db DBTX
}
