// Code generated by xo. DO NOT EDIT.

package models

import (
	"context"
	"time"
)

// User represents a row from 'public.users'.
type User struct {
	ID        int       `json:"id" db:"id"`
	Name      string    `json:"name" db:"name"`
	Email     string    `json:"email" db:"email"`
	AuthorID  int       `json:"author_id" db:"author_id"`
	CreatedAt time.Time `json:"created_at" db:"created_at"`
}

// Author represents a row from 'public.authors'.
type Author struct {
	ID   int    `json:"id" db:"id"`
	Name string `json:"name" db:"name"`
}

// Insert inserts the User to the database.
func (u *User) Insert(ctx context.Context, db DB) error {
	return nil
}

// Update updates a User in the database.
func (u *User) Update(ctx context.Context, db DB) error {
	return nil
}

// Delete deletes the User from the database.
func (u *User) Delete(ctx context.Context, db DB) error {
	return nil
}

// Author returns the Author associated with the User's AuthorID (FK).
func (u *User) Author(ctx context.Context, db DB) (*Author, error) {
	return AuthorByID(ctx, db, u.AuthorID)
}

// UserByID retrieves a row from 'public.users' as a User by primary key.
func UserByID(ctx context.Context, db DB, id int) (*User, error) {
	return nil, nil
}

// UserByEmail retrieves a row from 'public.users' as a User by unique index.
func UserByEmail(ctx context.Context, db DB, email string) (*User, error) {
	return nil, nil
}

// AuthorByID retrieves a row from 'public.authors' as an Author by primary key.
func AuthorByID(ctx context.Context, db DB, id int) (*Author, error) {
	return nil, nil
}
